pragma Singleton

import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick
import "../common"

Singleton {
  id: root

  property var  monitors:             []
  property bool loading:              false
  property bool persistenceAvailable: false

  property var  _lastEdits:     []
  property bool _pendingVerify: false

  signal monitorsLoaded()
  signal applyDone(bool hasErrors, string errorText)

  function findCurrentMode(m) {
    const target      = `${m.width}x${m.height}`;
    const rateRounded = Math.round(m.refreshRate);
    return m.availableModes.find(mode => {
      const match = mode.match(/^(\d+x\d+)@([\d.]+)Hz$/);
      return match
        && match[1] === target
        && Math.round(parseFloat(match[2])) === rateRounded;
    }) ?? m.availableModes[0]
      ?? `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}Hz`;
  }

  // One `hl.monitor` call, which is both what gets applied at runtime and what
  // gets written out for persistence -- the Lua config takes the same form for
  // each.
  //
  // This used to build `keyword monitor NAME,...` lines. Hyprland has parsed
  // this config as Lua since 0.55, and `hyprctl keyword` refuses outright under
  // the non-legacy parser -- "keyword can't work with non-legacy parsers. Use
  // eval." -- while still exiting 0, so every apply was a no-op. eval is the
  // replacement and is strictly better: it validates, answering an unknown
  // field or a string where an integer belongs with `error: ...` and exit 7.
  //
  // Field names and types are from probing the live parser, not from the wiki:
  // `disabled = true` (not `disable`, and not `mode = "disable"`), `transform`
  // wants an integer rather than the string hyprlang accepted, and `scale`
  // takes either.
  function buildMonitorLua(m) {
    // JSON.stringify for the strings: it quotes and escapes, and monitor names
    // are ASCII, where Lua and JSON string literals agree.
    const fields = [`output = ${JSON.stringify(m.name)}`];

    if (m.disabled) {
      fields.push("disabled = true");
    } else {
      const parsed = MonitorUtils.parseMode(m.selectedMode);
      const res  = parsed ? `${parsed.w}x${parsed.h}` : `${m.width}x${m.height}`;
      const rate = parsed ? parsed.rate : m.refreshRate.toFixed(2);

      fields.push(`mode = ${JSON.stringify(`${res}@${rate}`)}`);
      fields.push(`position = ${JSON.stringify(`${m.x}x${m.y}`)}`);
      fields.push(`scale = ${m.scale}`);
      if (m.transform !== 0)  fields.push(`transform = ${m.transform}`);
      if (m.mirrorOf  !== "") fields.push(`mirror = ${JSON.stringify(m.mirrorOf)}`);
    }

    return `hl.monitor({ ${fields.join(", ")} })`;
  }

  function buildFileContent(edits) {
    const lines = [
      "-- Generated by the Quickshell monitor manager, and overwritten on every",
      "-- apply. hyprland.lua loads it after its own hl.monitor calls, so what is",
      "-- here wins. Delete it to fall back to the defaults in hyprland.lua."
    ];
    for (const m of edits) lines.push(buildMonitorLua(m));
    return lines.join("\n") + "\n";
  }

  function refresh() {
    refreshDebounce.restart();
  }

  function _doRefresh() {
    if (loading) return;
    loading = true;
    queryProc.running = true;
  }

  function apply(edits) {
    // Guard against double-apply
    if (applyProc.running) return;
    _lastEdits = edits;

    // One eval for the whole set, rather than one per monitor. hyprctl wraps
    // the snippet as `return <snippet>;`, so several statements only parse
    // inside a function expression -- and going in together avoids a moment
    // where two monitors claim the same position.
    const calls = edits.map(buildMonitorLua).join("; ");
    applyProc.command = ["hyprctl", "eval", `(function() ${calls} end)()`];
    applyProc.running = true;
  }

  function persistToFile(edits) {
    const content = buildFileContent(edits);
    writeProc.command = [
      "python3", "-c",
      `open(${JSON.stringify(Paths.hyprStateDir + "/monitors.lua")}, 'w').write(${JSON.stringify(content)})`
    ];
    writeProc.running = true;
  }

  // eval echoes the whole snippet back before saying what was wrong:
  //   error: return (function() hl.monitor({ ... }) end)();:1: hl.monitor: field
  //   'transform': integer type requires a bool or an integer
  // Only the part after the line marker means anything to someone looking at an
  // error banner. Greedy on purpose, so a snippet that happens to contain
  // ":1:" still cuts at the last one.
  function _readableError(line) {
    const match = line.match(/^.*:\d+:\s*(.*)$/);
    return match ? match[1] : line.replace(/^error:\s*/, "");
  }

  function verifyApply() {
    const mismatches = [];
    for (const edit of _lastEdits) {
      const live = monitors.find(m => m.name === edit.name);
      if (!live) {
        mismatches.push(`${edit.name}: not found after apply`);
        continue;
      }
      if (live.disabled !== edit.disabled)
        mismatches.push(`${edit.name}: enabled state did not apply`);
      if (!edit.disabled && live.selectedMode !== edit.selectedMode)
        mismatches.push(`${edit.name}: mode ${edit.selectedMode} → got ${live.selectedMode}`);
    }
    _pendingVerify = false;
    applyDone(mismatches.length > 0, mismatches.join("; "));
  }

  onMonitorsLoaded: {
    if (_pendingVerify) verifyApply();
  }

  // Debounce timer — absorbs hotplug bursts (DisplayPort negotiation)
  Timer {
    id: refreshDebounce
    interval: 250
    repeat: false
    onTriggered: root._doRefresh()
  }

  // Check persistence availability on startup. Used to grep hyprland.lua's
  // source text for the old loader call, but hyprland.lua switched that
  // loader from `require` to `dofile`, so the old pattern stopped matching
  // and the check silently reported unavailable on every reload. What
  // persistence actually depends on is this directory existing to write
  // monitors.lua into and for hyprland.lua to dofile it back in -- so that
  // is what gets tested, and the next rewording of hyprland.lua's loader
  // can't break it again.
  Process {
    id: sourceCheck
    command: ["sh", "-c",
      "test -d \"$1\" && echo yes || echo no", "sh", Paths.hyprStateDir]
    running: true
    stdout: StdioCollector {
      onStreamFinished: {
        root.persistenceAvailable = text.trim() === "yes";
      }
    }
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "") console.warn("MonitorService sourceCheck:", text.trim());
      }
    }
  }

  // Query live monitor state
  Process {
    id: queryProc
    command: ["hyprctl", "-j", "monitors", "all"]
    running: false
    stdout: StdioCollector {
      onStreamFinished: {
        try {
          const raw = JSON.parse(text);
          root.monitors = raw.map(m => ({
            name:           m.name,
            description:    m.description,
            width:          m.width,
            height:         m.height,
            x:              m.x,
            y:              m.y,
            selectedMode:   root.findCurrentMode(m),
            scale:          m.scale,
            transform:      m.transform,
            disabled:       m.disabled,
            mirrorOf:       (() => {
              if (!m.mirrorOf || m.mirrorOf === "none") return "";
              // hyprctl -j returns mirrorOf as a stringified monitor ID (e.g. "0") rather than
              // the monitor name, so a direct display in the UI would show "0" instead of
              // "eDP-1".  Resolve it to the name so the rest of the codebase never sees raw IDs.
              const asId = parseInt(m.mirrorOf, 10);
              if (!isNaN(asId)) return raw.find(x => x.id === asId)?.name ?? "";
              return m.mirrorOf;
            })(),
            availableModes: m.availableModes,
          }));
          root.loading = false;
          root.monitorsLoaded();
        } catch (e) {
          console.error("MonitorService: JSON parse failed:", e);
          root.loading = false;
        }
      }
    }
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "") console.warn("MonitorService queryProc:", text.trim());
      }
    }
  }

  // Apply monitor configuration
  Process {
    id: applyProc
    running: false
    stdout: StdioCollector {
      onStreamFinished: {
        // hyprctl exits 0 for a refused keyword and 7 for a failed eval, but the
        // Process here does not surface the code, so stdout is still what says
        // whether it worked: "ok" or "error: ...".
        const lines  = text.trim().split("\n");
        const errors = lines.filter(l => l.trim() !== "" && l.trim() !== "ok");

        if (errors.length > 0) {
          root.applyDone(true, errors.map(root._readableError).join("; "));
        } else {
          root._pendingVerify = true;
          root.loading = true;
          // If queryProc is already running (poll timer race), it will finish
          // and call monitorsLoaded → verifyApply via _pendingVerify.
          // If it's idle, start it now.
          if (!queryProc.running) queryProc.running = true;
        }
      }
    }
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "") {
          root.applyDone(true, text.trim());
        }
      }
    }
  }

  // Write monitors.conf — fire and forget; log errors
  Process {
    id: writeProc
    running: false
    stdout: StdioCollector {}
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "")
          console.error("MonitorService: monitors.conf write failed:", text.trim());
      }
    }
  }

  // Listen for Hyprland events: hotplug and config reload
  Connections {
    target: Hyprland
    function onRawEvent(event) {
      // Never interrupt post-apply verification for config reload,
      // but allow hotplug events through so newly connected monitors
      // are detected even if we're mid-verify
      if (root._pendingVerify && event.name === "configreloaded") return;

      const triggers = ["monitoradded", "monitorremoved", "configreloaded"];
      if (triggers.includes(event.name)) root.refresh();
    }
  }
}
