pragma ComponentBehavior: Bound
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import QtQuick
import QtQuick.Layouts
import "../common"

// Per-workspace tiled layout picker. Hyprland 0.56 ships four tiled algorithms
// and `general:layout` only sets the default -- the per-workspace override is a
// workspace rule, which is what this writes.
Scope {
  id: root

  property var theme: DefaultTheme {}
  property string font: "AdwaitaMono Nerd Font"

  property bool isOpen: false
  property int selectedIndex: 0

  // Filled from `hyprctl -j activeworkspace` each time the picker opens, so the
  // rule always lands on the workspace that was focused at that moment rather
  // than on whatever the shell last happened to observe.
  property string wsName: ""
  property string currentLayout: ""

  // A layout chosen by ipc `set` while the workspace read is still in flight.
  // -1 means the read belongs to a plain open().
  property int pendingLayout: -1

  // Where the choices live between sessions. hyprland.lua pulls this back in
  // with `pcall(dofile, "workspace-layouts.lua")`, so every config load re-applies
  // them -- which covers a login, a `hyprctl reload`, and the reload Hyprland
  // does to itself when the config file changes.
  readonly property string storePath:
    Paths.hyprStateDir + "/workspace-layouts.lua"

  // Workspace name -> layout key, for every workspace ever chosen through here.
  // The file is rewritten whole on each choice, so this has to hold all of them,
  // not just the last one.
  property var saved: ({})
  property bool storeLoaded: false

  // The four algorithms compiled into Hyprland (Layout::Tiled::C*Algorithm).
  // `cells` is the schematic drawn on each tile, as x/y/w/h fractions of the
  // preview box -- drawn rather than iconised because no icon set has a symbol
  // that distinguishes master from dwindle, and both read as "split in two".
  readonly property var layouts: [
    {
      key: "dwindle", label: "Dwindle", hint: "recursive split",
      cells: [[0, 0, 0.48, 1], [0.52, 0, 0.48, 0.48], [0.52, 0.52, 0.48, 0.48]]
    },
    {
      key: "master", label: "Master", hint: "master + stack",
      cells: [[0, 0, 0.6, 1], [0.64, 0, 0.36, 0.31], [0.64, 0.345, 0.36, 0.31], [0.64, 0.69, 0.36, 0.31]]
    },
    {
      key: "monocle", label: "Monocle", hint: "one at a time",
      cells: [[0, 0, 1, 1]]
    },
    {
      // Columns running off both edges of the (clipped) preview box is the whole
      // point of the schematic -- that overflow is what scrolling looks like.
      key: "scrolling", label: "Scrolling", hint: "niri-style columns",
      cells: [[-0.18, 0, 0.34, 1], [0.2, 0, 0.34, 1], [0.58, 0, 0.34, 1], [0.96, 0, 0.34, 1]]
    }
  ]

  function toggle() { root.isOpen ? root.close() : root.open(); }

  // Read once, then believed. Re-reading after a write would race the write
  // itself, and nothing else on the machine touches this file.
  function loadStore() {
    if (root.storeLoaded) return;
    root.saved = root.parseStore(store.text());
    root.storeLoaded = true;
  }

  // The file is ours -- buildStore below wrote every line of it -- so matching
  // the one shape it emits is enough, and a line that does not match is dropped
  // rather than carried over. The header written into the file says as much: it
  // is generated state, not somewhere to hand-edit a rule. Anything more
  // elaborate belongs in hyprland.lua, which is loaded first and merged into.
  function parseStore(text) {
    const str = '"(?:[^"\\\\]|\\\\.)*"';
    const re = new RegExp("^\\s*hl\\.workspace_rule\\(\\{\\s*workspace\\s*=\\s*("
                          + str + ")\\s*,\\s*layout\\s*=\\s*(" + str + ")\\s*\\}\\)\\s*$");
    const out = ({});
    for (const line of String(text).split("\n")) {
      const match = line.match(re);
      if (!match) continue;
      try {
        // Lua and JSON string literals agree over ASCII, and workspace names
        // are ASCII -- so JSON.parse is the unquoting step for both captures.
        const ws  = JSON.parse(match[1]);
        const key = JSON.parse(match[2]);
        // A layout Hyprland no longer has would fail the rule at config load
        // and take the rest of the file with it.
        if (root.layouts.some(l => l.key === key)) out[ws] = key;
      } catch (e) {
        // Not something this wrote. Skipping it is the whole policy.
      }
    }
    return out;
  }

  function buildStore(map) {
    const lines = [
      "-- Generated by the Quickshell layout picker, and overwritten whenever a",
      "-- layout is chosen. hyprland.lua dofiles it after its own workspace",
      "-- rules, so what is here wins -- workspace_rule merges field by field, so",
      "-- the monitor / default / persistent settings there survive being",
      "-- overridden this way. Delete this file to go back to them."
    ];
    // Numeric-aware so 10 sorts after 9 rather than after 1, which only matters
    // for reading the file.
    for (const ws of Object.keys(map).sort((a, b) => a.localeCompare(b, "en", { numeric: true })))
      lines.push("hl.workspace_rule({ workspace = " + JSON.stringify(ws)
                 + ", layout = " + JSON.stringify(map[ws]) + " })");
    return lines.join("\n") + "\n";
  }

  function writeStore() {
    writeProc.command = ["sh", "-c",
                         'printf "%s" "$1" > "$2"',
                         "sh", root.buildStore(root.saved), root.storePath];
    writeProc.running = true;
  }

  // Opening is asynchronous: the overlay only appears once the workspace read
  // comes back. It takes a few milliseconds, and showing the panel first would
  // mean a visible frame with the wrong tile highlighted -- on a picker whose
  // entire job is "which one am I on", that frame is worse than the delay.
  function open() { root.pendingLayout = -1; readProc.running = true; }

  function close() { root.isOpen = false; }

  function apply(i) {
    const layout = root.layouts[Number(i)];
    if (!layout || root.wsName === "") return;

    root.close();

    // `hyprctl keyword` is rejected outright under the Lua config parser ("can't
    // work with non-legacy parsers"), so the rule goes through eval instead.
    // hl.workspace_rule merges into any rule already set for that workspace, so
    // the monitor / persistent / default fields from hyprland.lua survive this.
    //
    // JSON.stringify supplies the Lua string literal for the workspace name: it
    // quotes and escapes, and named workspaces ("special:magic") pass through as
    // the rule matcher expects them.
    applyProc.command = ["hyprctl", "eval",
      "hl.workspace_rule({ workspace = " + JSON.stringify(root.wsName)
        + ", layout = " + JSON.stringify(layout.key) + " })"];
    applyProc.running = true;

    // And write it down, because the eval above survives nothing: a config
    // reload replays hyprland.lua and puts its rules back. Written even when the
    // choice matches what is already stored -- the file is cheap and a no-op
    // rewrite is easier to reason about than a diff.
    root.loadStore();
    const next = Object.assign({}, root.saved);
    next[root.wsName] = layout.key;
    root.saved = next;
    root.writeStore();
  }

  function move(delta) {
    const n = root.layouts.length;
    root.selectedIndex = (root.selectedIndex + delta + n) % n;
  }

  Process {
    id: readProc
    command: ["hyprctl", "-j", "activeworkspace"]
    running: false
    stdout: StdioCollector {
      onStreamFinished: {
        let ws;
        try {
          ws = JSON.parse(text);
        } catch (e) {
          return; // hyprctl gone or mid-reload; leaving the picker shut is the honest failure
        }

        root.wsName = String(ws.name);
        root.currentLayout = String(ws.tiledLayout);
        root.loadStore(); // so the header can say whether this one is pinned

        // ipc `set` rides the same read -- it needs wsName just as much -- but
        // applies straight away instead of showing anything.
        if (root.pendingLayout >= 0) {
          const target = root.pendingLayout;
          root.pendingLayout = -1;
          root.apply(target);
          return;
        }

        // Land the cursor on the layout already in use, so the picker opens as a
        // readout and confirming without moving is a no-op rather than a change.
        const at = root.layouts.findIndex(l => l.key === root.currentLayout);
        root.selectedIndex = at >= 0 ? at : 0;

        root.isOpen = true;
      }
    }
  }

  Process { id: applyProc; running: false }

  Process {
    id: writeProc
    running: false
    stdout: StdioCollector {}
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "")
          console.error("LayoutSwitcher: workspace-layouts.lua write failed:", text.trim());
      }
    }
  }

  FileView {
    id: store
    path: root.storePath
    // Synchronous on purpose. apply() rewrites the file from `saved`, so acting
    // on a store that had not finished loading would drop every other
    // workspace's choice -- and the read happens on a keypress, where an async
    // one has nowhere to wait. The file is a handful of lines and this runs once.
    blockLoading: true
    // Absent until something has been chosen, which is the normal state on a
    // fresh machine rather than an error worth logging on every startup.
    printErrors: false
  }

  IpcHandler {
    target: "layout"

    function toggle(): void { root.toggle(); }
    function open(): void   { root.open(); }
    function close(): void  { root.close(); }

    // Set a layout on the focused workspace without showing the picker, for
    // anyone who wants a direct bind to one algorithm.
    function set(name: string): void {
      const i = root.layouts.findIndex(l => l.key === name);
      if (i < 0) return;
      root.pendingLayout = i;
      readProc.running = true;
    }
  }

  Scrim { active: overlay.visible; color: root.theme.bgOverlay; onClicked: root.close() }

  PanelWindow {
    id: overlay
    visible: root.isOpen
    focusable: true
    color: "transparent"

    WlrLayershell.layer: WlrLayer.Overlay
    WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive
    WlrLayershell.namespace: "quickshell-layout"

    exclusionMode: ExclusionMode.Ignore

    anchors { top: true; bottom: true; left: true; right: true }

    MouseArea {
      anchors.fill: parent
      onClicked: root.close()
    }

    Rectangle {
      anchors.centerIn: parent
      width: menuColumn.implicitWidth + 48
      height: menuColumn.implicitHeight + 40
      radius: 16
      color: root.theme.bgBase
      border.color: root.theme.bgBorder
      border.width: 1
      focus: true

      Keys.onEscapePressed: root.close()

      Keys.onPressed: event => {
        if (event.key === Qt.Key_Left || event.key === Qt.Key_H) {
          event.accepted = true; root.move(-1);
        } else if (event.key === Qt.Key_Right || event.key === Qt.Key_L) {
          event.accepted = true; root.move(1);
        } else if (event.key === Qt.Key_Return || event.key === Qt.Key_Enter || event.key === Qt.Key_Space) {
          event.accepted = true; root.apply(root.selectedIndex);
        } else if (event.key >= Qt.Key_1 && event.key <= Qt.Key_4) {
          // Number keys pick and commit in one press. Nothing here is
          // destructive -- the worst case is a re-tile you undo with another
          // keypress -- so the confirm step SessionMenu needs would only be in
          // the way.
          event.accepted = true;
          root.apply(event.key - Qt.Key_1);
        }
      }

      MouseArea {
        anchors.fill: parent
        onClicked: event => event.accepted = true
      }

      ColumnLayout {
        id: menuColumn
        anchors.centerIn: parent
        spacing: 14

        Text {
          Layout.alignment: Qt.AlignHCenter
          // Every choice made here is written down, which is invisible
          // otherwise -- so a workspace that already carries a saved override
          // says so, and the absence of it on the rest explains what the word
          // means without a legend.
          // Single spaces around the separator, to match the "layout ·
          // workspace" one alongside it -- the wider "  ·  " used for the
          // subtitles elsewhere reads as a bigger break than this is.
          text: "layout · workspace " + root.wsName
                + (root.saved[root.wsName] ? " · remembered" : "")
          color: root.theme.textSecondary
          font { pixelSize: 11; family: root.font }
        }

        RowLayout {
          Layout.alignment: Qt.AlignHCenter
          spacing: 12

          Repeater {
            model: root.layouts

            Rectangle {
              id: tile
              required property var modelData
              required property int index

              readonly property bool isSelected: root.selectedIndex === index
              readonly property bool isCurrent: root.currentLayout === modelData.key

              implicitWidth: 118
              implicitHeight: 118
              radius: 12
              color: isSelected ? root.theme.bgSelected
                   : tileHover.containsMouse ? root.theme.bgHover
                   : root.theme.bgSurface

              border.width: (isSelected || isCurrent) ? 1 : 0
              border.color: isSelected ? root.theme.accentPrimary : root.theme.bgBorder

              Behavior on color { ColorAnimation { duration: 120 } }

              Accessible.role: Accessible.Button
              Accessible.name: tile.isCurrent
                               ? tile.modelData.label + ", current layout"
                               : tile.modelData.label

              ColumnLayout {
                anchors.centerIn: parent
                spacing: 8

                Item {
                  Layout.alignment: Qt.AlignHCenter
                  implicitWidth: 52
                  implicitHeight: 34
                  clip: true // scrolling's outer columns are meant to run off the edge

                  Repeater {
                    model: tile.modelData.cells

                    Rectangle {
                      required property var modelData
                      x: modelData[0] * parent.width
                      y: modelData[1] * parent.height
                      width: modelData[2] * parent.width
                      height: modelData[3] * parent.height
                      radius: 2
                      color: tile.isSelected ? root.theme.accentPrimary : root.theme.textMuted
                      Behavior on color { ColorAnimation { duration: 120 } }
                    }
                  }
                }

                Text {
                  Layout.alignment: Qt.AlignHCenter
                  text: tile.modelData.label
                  color: tile.isSelected ? root.theme.textPrimary : root.theme.textMuted
                  font { pixelSize: 11; bold: tile.isSelected; family: root.font }
                }

                Text {
                  Layout.alignment: Qt.AlignHCenter
                  // The current layout says so; the rest explain themselves.
                  text: tile.isCurrent ? "current" : tile.modelData.hint
                  color: tile.isCurrent ? root.theme.accentGreen : root.theme.textMuted
                  font { pixelSize: 9; family: root.font }
                }
              }

              MouseArea {
                id: tileHover
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onEntered: root.selectedIndex = tile.index
                onClicked: root.apply(tile.index)
              }
            }
          }
        }

        Text {
          Layout.alignment: Qt.AlignHCenter
          text: "←→ to choose  ·  1-4 to jump  ·  enter to apply  ·  esc to cancel"
          color: root.theme.textMuted
          font { pixelSize: 10; family: root.font }
        }
      }
    }
  }
}
