
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
--
-- The displays are not declared here, because this file is shared: Syncthing
-- replicates it to every machine, so a monitor block written for one of them is
-- wrong on all the others. It used to hold HDMI-A-1 and DP-1 at scale 1.67 --
-- the desktop's two screens -- which the laptop then had to override with a
-- generated monitors.lua just to drive its one panel.
--
-- hosts/<hostname>.lua declares this machine's outputs instead, and returns a
-- table naming which is primary and which is secondary. The workspace rules
-- further down read those names, so the *policy* (1-5 here, 6-10 there) stays
-- in this file and shared, while the *hardware* stays per host.
--
-- The host is chosen at build time: home/hyprland.nix substitutes the
-- machine's name, taken from the flake's mkHome argument, into the path
-- below. The old runtime hostname lookup, its domain stripping, its pcall
-- and its fail-loud banner are gone.
--
-- An unknown host is NOT an evaluation error, and an earlier version of this
-- comment said it was. home/hyprland.nix only substitutes the name; nothing
-- checks the file exists, so the pcall below is what actually happens. The
-- loud failure lives in flake.nix's host-config-files check instead, which
-- fails the build when a host in hostConfigs has no file here.
local loaded, hostCfg = pcall(dofile, "@hyprSource@/hosts/@host@.lua")
if not loaded or type(hostCfg) ~= "table" then
    -- No file for this machine: no monitor declarations, which leaves Hyprland
    -- to light up whatever it finds at its preferred mode, and no primary,
    -- which makes the workspace rules below no-ops. That is a working desktop
    -- on an unknown machine, not a broken one -- copy a hosts/ file to this
    -- machine's name to pin it down.
    hostCfg = {}
end

-- Whatever the Quickshell monitor manager last applied, which it rewrites in
-- full on every successful apply. It loads after the two defaults above, so a
-- saved layout wins over them -- and until something has been applied the file
-- does not exist and the pcall makes this a no-op, leaving the defaults in
-- charge.
--
-- The panel greps this very line to decide whether to offer persistence at all;
-- without it, it applies to the running session and says so, and the file it
-- writes is never read back. Same mechanism workspace-layouts.lua uses below.
-- State, not source: quickshell writes this. pcall stays because the file does
-- not exist until the monitor panel has been used once, and dofile raises.
pcall(dofile, "@hyprState@/monitors.lua")


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
--
-- foot rather than kitty, and the reason is what it leaves out. foot is
-- Wayland-only with no X11 path, and it has no tabs, no splits and no scripting
-- layer -- Hyprland and tmux already do all three on this desktop, so carrying
-- kitty's copy of them buys nothing. It also draws sixel, which is what put lf
-- in a foot window below, so SUPER+Q and SUPER+E now agree on the terminal.
--
-- What it costs: foot has neither remote control nor a config reload, so a
-- theme switch does not reach a foot window that is already open. The switcher
-- writes foot/theme-colors.ini and the next window reads it -- see the note in
-- theme-switcher/Theme.qml. kitty followed live over the socket in kitty.conf,
-- and it is still installed and still recoloured that way; open one when you
-- want to watch a theme land without opening a window for it.
local terminal    = "foot"

-- The file manager is lf, and the reason is the dependency set behind the
-- alternatives. dolphin was here, and it pulls 601 packages on Debian 13 -- the
-- whole of KDE Frameworks -- to open a folder. pcmanfm-qt takes 219 and needs
-- QT_QPA_PLATFORMTHEME set before its icons follow the theme switcher. lf takes
-- one: a single Go binary with no toolkit at all, wearing whatever palette the
-- terminal around it has.
--
-- foot is named here rather than inherited from `terminal` above, because this
-- line needs it for a reason of its own and would keep needing it if SUPER+Q
-- ever moved back. lf can put an image in its preview pane, and sixel is the
-- only graphics format it passes through. foot 1.21.0 draws sixel; kitty 0.41.1
-- does not, measured with a hand-built one and with chafa. In kitty that pane
-- falls back to coloured blocks, and the way round it -- writing kitty's own
-- protocol past lf to /dev/tty -- corrupts the panes on any file large enough to
-- take chafa a moment to decode. lf/preview carries the timings.
--
-- It costs what `terminal` above costs: an lf window open across a theme change
-- keeps the old palette until it is restarted.
--
-- `--app-id lf` is what makes the window addressable. Without it this is another
-- foot window, indistinguishable from a shell in the SUPER+TAB switcher and
-- unreachable by any windowrule that wants to treat it differently.
local fileManager = "foot --app-id lf lf"

-- Both of these used to be rofi (`-show drun` and `-show window`). The launcher
-- and the window switcher are quickshell surfaces now, which means they follow
-- the theme switcher like everything else on screen does -- rofi was the last
-- thing that stayed Tokyo Night no matter what the rest of the desktop did.
local menu         = "qs ipc call launcher toggle"
local switchWindow = "qs ipc call switcher toggle"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)
hl.on("hyprland.start", function ()
  -- uwsm owns this session. It started the compositor from
  -- /usr/share/wayland-sessions/hyprland-uwsm.desktop, and
  -- wayland-wm@hyprland.desktop.service is Type=notify -- so graphical-session.target
  -- is NOT reached until the line below notifies systemd. quickshell.service
  -- and bt-agent.service are WantedBy that target and enabled, so they start
  -- here, after the environment is in place, with no race left to lose. That
  -- race is why this file used to start them by hand and why their units used
  -- to forbid `systemctl --user enable`.
  --
  -- What this replaces: a stop of graphical-session.target, a
  -- `dbus-update-activation-environment --systemd --all` behind an `env -u`
  -- blocklist, and an explicit start of a hand-written hyprland-session.target.
  -- uwsm does all three, and its source agrees with every conclusion that code
  -- was written from: prepare-env.sh exports XDG_SESSION_TYPE=wayland
  -- unconditionally -- the variable whose absence sent every Electron flatpak to
  -- X11 -- and Varnames.never_export holds NOTIFY_SOCKET, XDG_SEAT,
  -- XDG_SESSION_ID and XDG_VTNR, the same blocklist, plus XDG_SEAT_PATH and
  -- XDG_SESSION_PATH. It exports the whole environment difference rather than an
  -- allowlist, which is the trap this file fell into once. Read in the installed
  -- source on both machines: uwsm 0.26.4 here, 0.26.1 on epiphany.
  --
  -- The teardown is gone too. wayland-wm@.service declares OnSuccess= AND
  -- OnFailure=wayland-session-shutdown.target with
  -- JobMode=replace-irreversibly, so a compositor that exits and one that
  -- crashes both take the session down with them. The hyprland.shutdown handler
  -- that used to do this could not cover the crash -- which is exactly why the
  -- deleted code had to stop the target on start as well as on shutdown.
  --
  -- finalize exports WAYLAND_DISPLAY and DISPLAY, plus everything named in
  -- UWSM_FINALIZE_VARNAMES -- which /usr/share/uwsm/plugins/hyprland.sh fills
  -- with HYPRLAND_INSTANCE_SIGNATURE, HYPRLAND_CMD, HYPRCURSOR_THEME,
  -- HYPRCURSOR_SIZE, XCURSOR_SIZE and XCURSOR_THEME. That covers the cursor
  -- variables set with hl.env further down this file. It does NOT cover PATH,
  -- which this repo does not hand to uwsm's env plugin at all: PATH is set by
  -- the wrapper script itself, in home/session.nix's compositorPath (unlike
  -- calango-desktop, calango-nix has no tracked uwsm/env).
  --
  -- The `||` is the whole alarm. Started outside uwsm -- the plain "Hyprland"
  -- session entry, or a bare TTY -- finalize exits non-zero and nothing else in
  -- this desktop comes up: no shell, no portal, no idle lock. Inside uwsm a
  -- failure here is louder still: wayland-wm@.service has TimeoutStartSec=30,
  -- so systemd kills the compositor and shuts the session down rather than
  -- leaving it half-started.
  --
  -- notify's second argument is a display time in milliseconds, not a flag: 0
  -- means zero milliseconds and the banner is never seen. There is no "until
  -- dismissed" value, so it gets a minute. Icon 3 is Error, and colour 0 means
  -- the default colour for that icon.
  hl.exec_cmd("uwsm finalize || hyprctl notify 3 60000 0 "
              .. "'not a uwsm session: log out, pick Hyprland (uwsm-managed)'")

  -- hypridle is NOT started here, and the line that used to do it was starting a
  -- second copy of a daemon systemd was already running.
  --
  -- The hypridle package ships /usr/lib/systemd/user/hypridle.service and enables
  -- it, so it is WantedBy=graphical-session.target like quickshell.service and
  -- bt-agent.service above -- the same target this comment block spends forty
  -- lines explaining that uwsm reaches with the environment already in place. On
  -- suffer the enablement is a symlink at
  -- /etc/systemd/user/graphical-session.target.wants/hypridle.service, put there
  -- by the package rather than by this repo.
  --
  -- Both really did run. Caught 2026-08-11 with two live processes: pid 3131,
  -- child of this exec_cmd at 19:15:08, and pid 3192, started by the user manager
  -- one second later. It hid for months because the duplication was harmless --
  -- two `loginctl lock-session` calls at five minutes are idempotent, two `dpms
  -- off` at five and a half are the same picture, and `lock_cmd = pidof hyprlock
  -- || /usr/bin/hyprlock --config ...` already refused to start a second
  -- locker. Adding a listener that suspends the machine is what made it worth
  -- finding.
  --
  -- If a host turns up where the package does not enable it, the fix is
  -- `systemctl --user enable --now hypridle.service` on that host, not this line
  -- coming back: a hand-started daemon has no ordering against
  -- graphical-session.target, no Restart=on-failure, and no way to be restarted
  -- other than pkill.

  -- Clipboard history, read back by the quickshell picker on SUPER+SHIFT+V.
  -- cliphist only records what is handed to it, so without these two watchers
  -- running there is no history at all.
  --
  -- The text watcher skips anything advertising x-kde-passwordManagerHint, which
  -- is the mime type password managers set on a copied secret. Without the guard
  -- every password you copy lands in a plaintext db under ~/.cache and stays
  -- there for the next 750 entries. It is not airtight -- a manager that does not
  -- set the hint is still recorded -- so treat the history as readable, not safe.
  -- wl-clip-persist was tried here and removed. It is the wlroots stand-in for
  -- Plasma's Klipper: it grabs ownership of the selection so clipboard contents
  -- survive the program that copied them exiting. Two findings against it:
  --
  --   1. It did not fix Bitwarden, which was why it was installed. A mime-type
  --      probe sampling the selection every 0.3s recorded ZERO selection events
  --      while copying from Bitwarden under --ozone-platform=wayland. The app
  --      never creates an offer there at all, so there is nothing to persist.
  --   2. It appears to break the XWayland clipboard. Bitwarden on x11 worked
  --      before it was installed, failed while it was running, and worked again
  --      once it was stopped. Hyprland bridges the X11 selection into the
  --      Wayland one, and a second owner contending for that selection is a
  --      plausible way for an XWayland copy to vanish. Single A/B, not proof.
  --
  -- Binary is still at ~/.cargo/bin/wl-clip-persist if this is worth revisiting.

  -- Guarded with pgrep because a second watcher on the same mime type means every
  -- copy is stored twice, and the history fills with pairs. Kept as a belt-and-
  -- braces measure: hyprland.start does NOT fire on `hyprctl reload` -- tested
  -- with a marker command in this handler, which stays unwritten across a reload
  -- -- so the only known trigger is compositor startup, where nothing is running
  -- to duplicate.
  --
  -- This used to cite the unguarded hypridle above as a second proof, on the
  -- grounds that it never produced a duplicate either. It did produce one, every
  -- login, just not from a reload; see the block where that line used to be. The
  -- reload finding stands on the marker test alone.
  hl.exec_cmd("pgrep -f 'wl-paste --type text --watch' >/dev/null || "
              .. "wl-paste --type text --watch sh -c '"
              .. "wl-paste --list-types | grep -qi x-kde-passwordManagerHint || cliphist store'")
  hl.exec_cmd("pgrep -f 'wl-paste --type image --watch' >/dev/null || "
              .. "wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

-- XCURSOR_THEME has to be in the environment before a client starts, so it
-- cannot come from gsettings the way the GTK theme does. Named explicitly
-- rather than left at "default": that is a real theme directory carrying only
-- "Inherits=Adwaita", and XWayland and some toolkits do not follow the
-- indirection, which is how you end up with the X11 cross cursor over some
-- windows. ~/.local/bin/apply-gtk-theme keeps the GTK-side keys in step.
--
-- No HYPRCURSOR_THEME: no hyprcursor theme is installed (nothing ships a
-- manifest.hl), so Hyprland falls back to this XCursor theme. HYPRCURSOR_SIZE
-- stays so the fallback matches if one is ever added.
--
-- And naming the theme here is necessary but was never sufficient. For the
-- whole life of this line the theme it names could not be found: Hyprland
-- resolves it through Nix's libXcursor, whose compiled-in search path is
-- ~/.local/share/icons, ~/.icons and its own store directory -- never
-- /usr/share/icons, where Debian's adwaita-icon-theme keeps its cursors.
-- themePaths() came back empty and the compositor drew its own built-in
-- arrow instead. home/default.nix's home.pointerCursor is what puts the
-- theme on that path; the full measurement lives in its comment. Do not
-- "simplify" that option into a plain home.packages entry -- the profile's
-- share/icons is not on the path either.
--
-- Adding a hyprcursor theme is deliberately NOT the answer here, and was
-- measured rather than assumed: adwaita-icon-theme 50.0 ships no SVG cursor
-- sources at all, so hyprcursor-util --extract yields PNG at 24/30/36/48/72/96
-- with resize_algorithm = none -- the same raster data the XCursor theme
-- already holds. eDP-1 runs at scale 1.25, so Hyprland asks for size 30, and
-- 30 is one of those six. A conversion would change nothing on screen.
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Border colours are owned by the quickshell theme switcher: on every theme change
-- it writes theme-borders.conf and runs `hyprctl keyword` for the live update.
-- Reading that file back here is what makes a theme survive `hyprctl reload` --
-- without it the hardcoded fallbacks below silently win and the borders snap back
-- to cyan/green. Fallbacks are used only when the file doesn't exist yet.
local function themeBorders()
    local active   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 }
    local inactive = "rgba(595959aa)"

    local f = io.open("@hyprState@/theme-borders.conf", "r")
    if not f then return active, inactive end

    for line in f:lines() do
        local a = line:match("col%.active_border%s*=%s*(.+)")
        if a then
            local cols = {}
            for c in a:gmatch("rgba?%b()") do cols[#cols + 1] = c end
            if #cols > 0 then
                active = { colors = cols, angle = tonumber(a:match("(%d+)%s*deg")) or 45 }
            end
        end

        local i = line:match("col%.inactive_border%s*=%s*(rgba?%b())")
        if i then inactive = i end
    end
    f:close()

    return active, inactive
end

local activeBorder, inactiveBorder = themeBorders()

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = activeBorder,
            inactive_border = inactiveBorder,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        -- Dim unfocused windows here rather than inside each app. A terminal
        -- doing its own fading (kitty's inactive_text_alpha) only dims glyphs,
        -- not background cells, which seams anything drawing a coloured block
        -- with glyph end-caps — tmux status pills, powerline prompts. The
        -- compositor dims the whole surface, so the two stay in step.
        -- 0.15 is roughly what kitty's 0.85 text alpha used to look like.
        dim_inactive = true,
        dim_strength = 0.15,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 3,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
--
-- `speed` is a DURATION in ds (1ds = 100ms), so a smaller number is a faster
-- animation. Rather than hand-tuning seventeen values, scale them all with one
-- knob: 1.0 is the stock config, 0.5 runs everything at double speed.
local animSpeed = 0.5

local function anim(spec)
    if spec.speed then
        spec.speed = spec.speed * animSpeed
    end
    hl.animation(spec)
end

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- niri's two easing curves, written as the standard cubic-bezier
-- approximations of the Penner easings it names by string.
hl.curve("niriOutExpo",    { type = "bezier", points = { {0.19, 1},    {0.22, 1}    } })
hl.curve("niriOutQuad",    { type = "bezier", points = { {0.25, 0.46}, {0.45, 0.94} } })

-- Springs, ported from niri's defaults. Hyprland parameterises a spring by
-- absolute damping and niri by damping RATIO, so crossing over means
--
--     dampening = 2 * zeta * sqrt(stiffness * mass)      -- mass = 1 here
--
-- niri's defaults, and what they land on:
--     window-movement / -resize / overview   zeta 1.0, k  800 -> 56.568542
--     workspace-switch                       zeta 1.0, k 1000 -> 63.245553
--     config-notification-open-close         zeta 0.6, k 1000 -> 37.947332
--
-- zeta 1.0 is critically damped -- no overshoot at all. What was here before
-- was
--     stiffness = 71.2633 / animSpeed^2,  dampening = 15.8273644 / animSpeed
-- which works out to zeta 0.9374 (a slight bounce) at k 285, so niri's springs
-- are both tighter and about 1.7x quicker. Those numbers are kept here in case
-- the bounce is ever wanted back.
--
-- Note these are deliberately NOT divided by animSpeed the way the old spring
-- was. They are niri's values as it ships them, not a curve tuned against this
-- config's speed knob. The consequence: animSpeed no longer reaches the
-- springs. It still scales every duration below, but these three stay put. To
-- bring them back under the knob, divide stiffness by animSpeed^2 and dampening
-- by animSpeed, which is what the old spring did and why it squared.
hl.curve("niriMove",   { type = "spring", mass = 1, stiffness = 800,  dampening = 56.568542 })
hl.curve("niriWs",     { type = "spring", mass = 1, stiffness = 1000, dampening = 63.245553 })
hl.curve("niriNotify", { type = "spring", mass = 1, stiffness = 1000, dampening = 37.947332 })

anim({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
anim({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
-- <- niri window-movement / window-resize. `speed` is inert on a spring leaf --
-- Hyprland takes the pace from stiffness -- so the number here does nothing and
-- is left at its old value rather than invented.
anim({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "niriMove" })
-- <- niri window-open: 150 ms ease-out-expo. 1.5 * animSpeed 0.5 = 75 ms.
-- niri has no popin equivalent, so the style is dropped; add
-- `style = "popin 87%"` back if the scale-up is wanted with niri's curve.
anim({ leaf = "windowsIn",     enabled = true,  speed = 1.5,  bezier = "niriOutExpo" })
-- <- niri window-close: 150 ms ease-out-quad, likewise 75 ms after scaling.
anim({ leaf = "windowsOut",    enabled = true,  speed = 1.5,  bezier = "niriOutQuad" })
anim({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
anim({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
anim({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
-- <- niri config-notification-open-close (zeta 0.6, the one bouncy default).
anim({ leaf = "layers",        enabled = true,  speed = 3.81, spring = "niriNotify" })
anim({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
anim({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
anim({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
anim({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
-- <- niri workspace-switch (zeta 1.0, k 1000).
anim({ leaf = "workspaces",    enabled = true,  speed = 1.94, spring = "niriWs",       style = "fade" })
anim({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
anim({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
-- <- niri overview-open-close (same spring as window movement).
anim({ leaf = "zoomFactor",    enabled = true,  speed = 7,    spring = "niriMove" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- Pin workspaces to monitors. Without these rules Hyprland hands workspace N to
-- monitor ID N-1, and the IDs come from DRM connector enumeration order rather
-- than the order the monitors are declared -- on the desktop DP-1 enumerates as
-- ID 0, so it would claim workspace 1 despite the left screen being primary.
--
-- The output names come from hosts/<hostname>.lua, loaded at the top. A machine
-- with one display names no secondary, and everything lands on the primary --
-- better than the old behaviour, which pinned 6-10 to a DP-1 that did not exist
-- on the laptop and stranded them.
local primary   = hostCfg.primary
local secondary = hostCfg.secondary or primary

local vscodeWorkspace = 2
local youtubeWorkspace = 10

if primary then
    for i = 1, 5 do
        if i ~= vscodeWorkspace then -- defined on its own below, with the monocle layout
            hl.workspace_rule({ workspace = tostring(i), monitor = primary, default = (i == 1) })
        end
    end

    for i = 6, 10 do
        hl.workspace_rule({
            workspace  = tostring(i),
            monitor    = secondary,
            default    = (i == 6),
            persistent = (i == youtubeWorkspace), -- keep it alive so the rule below always lands
        })
    end

    -- The VSCode workspace. `persistent` keeps it alive while empty so the rules
    -- below always have somewhere to land.
    hl.workspace_rule({
        workspace  = tostring(vscodeWorkspace),
        monitor    = primary,
        layout     = "monocle",
        persistent = true,
    })
end

-- Layouts picked through the Quickshell layout switcher (SUPER+SHIFT+space),
-- which rewrites this file on every choice. It loads here, after the rules
-- above, so a chosen layout wins over them -- workspace_rule merges field by
-- field, so the monitor / default / persistent settings above survive being
-- overridden this way, and only `layout` changes.
--
-- pcall because the file does not exist until a layout has been chosen, and a
-- missing module is a raised error rather than a nil return. Delete the file to
-- go back to the defaults above.
-- Same as monitors above: written by quickshell's layout switcher, absent
-- until first use.
pcall(dofile, "@hyprState@/workspace-layouts.lua")

-- Send every VSCode window to that workspace. `silent` means opening a new one
-- (or a new project window) does not drag focus off whatever you are on.
hl.window_rule({
    name      = "vscode-to-monocle-workspace",
    match     = { class = "^code$" },
    workspace = tostring(vscodeWorkspace) .. " silent",
})

-- Same treatment for the YouTube PWA. Chrome app windows take their class from
-- the shortcut id rather than the .desktop StartupWMClass, so this matches
-- chrome-<app-id>-<profile> and not crx_<app-id>.
hl.window_rule({
    name      = "youtube-to-media-workspace",
    match     = { class = "^chrome-agimnkijcaahngcdmfeangaknmldooml-Profile_2$" },
    workspace = tostring(youtubeWorkspace) .. " silent",
})

-- The scratchpad crowd: apps you dip into and dismiss rather than work in, so
-- they live on the special workspace SUPER+S toggles instead of taking a tile
-- on whatever you were doing. Floating, because a special workspace tiles like
-- any other and a single window would otherwise fill the screen.
--
-- No `silent` here, unlike the two rules above: those assign windows that open
-- by themselves and must not steal focus, while these you launch on purpose, so
-- the scratchpad slides open with the window you just asked for. Add `silent`
-- if you would rather they stash themselves quietly.
--
-- Both classes are what the windows actually report on wayland, not what their
-- .desktop advertises -- 1Password's StartupWMClass says "1Password" and the
-- window says "1password". Add another app by widening the alternation, after
-- checking it with `hyprctl clients -j`.
hl.window_rule({
    name      = "scratchpad-apps",
    match     = { class = "^(1password|org\\.signal\\.Signal)$" },

    workspace = "special:magic",
    float     = true,
})

-- Replace the password manager with a black rectangle in anything that captures
-- the screen. Same class as the scratchpad rule above; widen the alternation to
-- `^(1password|org\\.signal\\.Signal)$` to cover Signal too.
--
-- THE FIELD NAME IS LOAD-BEARING. It is `no_screen_share`, snake_case. The
-- Hyprland wiki documents this rule as `noscreenshare`, which is the old conf
-- syntax and is **silently ignored** under the lua parser -- and rule fields are
-- not validated at all (`hl.window_rule{ __bogus__ = 1 }` is accepted without a
-- word), so the wrong spelling is not an error you would ever see. It is a
-- privacy rule that quietly does nothing, failing toward leaking rather than
-- toward a visible glitch. Same trap as `hyprctl keyword` under this parser.
-- Upstream knows the wiki is wrong: hyprwm/Hyprland discussion #12417.
--
-- Measured on 0.56.0 rather than assumed, by capturing a region with grim --
-- which goes through wlr-screencopy, the same path a screencast takes -- and
-- counting non-black pixels: 100% visible with `noscreenshare`, 0.2% with
-- `no_screen_share`, and back to 100% once the rule was disabled.
--
-- This blocks the whole screencopy path, so your own `grim` screenshots get the
-- black rectangle as well. niri's equivalent takes a mode ("screencast" vs
-- "screen-capture") and can block casts while still allowing screenshots;
-- Hyprland's is a boolean and cannot.
hl.window_rule({
    name  = "blackout-password-manager",
    match = { class = "^(1password)$" },

    no_screen_share = true,
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,

        -- 1 (Hyprland's default) scrolls the camera the LEAST amount that
        -- makes the focused column fully visible; 0 centers the focused column
        -- on every focus change. This is a plain setting now: Hyprland decides
        -- the camera and nothing in this file second-guesses it.
        --
        -- It was not always. A 241-line rule hooked window.active, window.open
        -- and window.close and set this option per event from the column
        -- geometry, so a column that could not share the screen with its
        -- neighbour was centered and every other one was not. It worked, and it
        -- was a great deal of machinery on every focus change in the session --
        -- three geometry helpers, a reentry guard, a remembered centered state,
        -- and a two-hop focus round trip to undo a centering, because setting
        -- the option back to 1 does not un-center anything on its own. Removed
        -- deliberately, not by accident. `git log` this file for the seven
        -- commits that built it if the behaviour is ever wanted back.
        --
        -- Read the history before changing this back. 0 was tried first, to get
        -- niri's `center-focused-column = "on-overflow"`, and it does not mean
        -- what it looks like. It means "always center", and the conditional
        -- half comes from the camera, which centers the whole tape when the
        -- tape fits:
        --
        --     // if the content fits in viewport, center it
        --     if (maxExtent < usablePrimary)
        --         m_offset = std::round((maxExtent - usablePrimary) / 2.0);
        --     -- ScrollTapeController.cpp:222-224, v0.55.4
        --
        -- `<` is strict, and with the stock 0.5 width two columns are EXACTLY
        -- as wide as the screen, so the test is false and a two-terminal
        -- workspace centered the focused terminal with the other one hanging
        -- half off the edge:
        --
        --     x= -352 w=739 right= 387   <- half off the left edge
        --     x=  401 w=739 right=1140   <- focused, centered
        --
        -- centerCol lives at ScrollingAlgorithm.cpp:403-413 and fitCol beside
        -- it. Neither is reachable from a dispatcher: `center` is the only
        -- layout message that touches the camera alone, every `fit` mode
        -- resizes columns, and `move <px>` scrolls but then focuses whatever
        -- lands in the middle. Focus is the camera control here.
        focus_fit_method = 1,

        -- The camera does not chase focus. Hovering still focuses -- follow_mouse
        -- is untouched -- the view simply stops moving on its own.
        --
        -- Measured, with follow_focus at its default of true: hovering a column
        -- that was cut off focused it, the camera scrolled to fit it, that scroll
        -- slid a different window under a pointer that had not moved, and focus
        -- flipped again. One hover produced three focus changes at x=94..110 in
        -- about a second. Parking the camera removes the second link and the loop
        -- cannot start.
        --
        -- The cost, stated so nobody re-enables this by accident: a focused
        -- column can sit entirely off screen and nothing scrolls it back. The
        -- ways back are the three-finger swipe, SUPER+wheel, SUPER+comma/period,
        -- and SUPER+CTRL+H/L for the other monitor -- which warps the pointer
        -- with you, since cursor:no_warps is false.
        follow_focus = false,

        -- The widths are a preference now, not a mechanism. They were chosen
        -- while focus_fit_method was 0, to keep every combination that fits
        -- strictly UNDER the monitor width, since at equality the camera stops
        -- centering the tape. Under 1 that only decides whether a tape which
        -- fits sits centered with a small margin (0.49: x=37..761 and
        -- 775..1499 on a 1536 px monitor) or edge to edge (0.5). Kept for the
        -- margin. 0.667 is spelled 0.66 for the same reason: 0.333 * 1536 +
        -- 0.667 * 1536 = 1536.0000000000002, which is over, not equal.
        column_width           = 0.49,
        explicit_column_widths = "0.333, 0.49, 0.66, 0.95",
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(

        -- Honour xdg-activation requests instead of only marking the window
        -- urgent. This is what makes the "View" button on a notification
        -- actually jump to the window: quickshell invokes the action over
        -- D-Bus, the app asks to be raised, and with this off Hyprland denies
        -- the raise and sets the urgent hint -- which is the workspace blink.
        --
        -- The tradeoff is that any app can now pull focus this way, not just
        -- ones you asked to. Opt individual offenders back out with
        --   hl.windowrule("suppressevent activatefocus", "class:^(foo)$")
        focus_on_activate = true,
    },
})


-------------------
---- XWAYLAND -----
-------------------

-- X11 has no per-output scale, so XWayland clients always render at scale 1 and
-- get resampled to the monitor's 1.67. The only real fix is running the app
-- natively on Wayland; this just picks the least ugly resampling for the ones
-- that cannot.
--
-- The default filter is nearest neighbour, which at a fractional factor
-- duplicates pixels unevenly: glyph stems come out 1px wide in some places and
-- 2px in others, and the grey antialiasing fringes the app drew get replicated
-- as hard blocks. Text reads as jagged and un-antialiased. Bilinear resampling
-- blurs slightly instead, which is what KWin does unconditionally -- no
-- resolution is recovered either way, it just stops looking broken.
hl.config({
    xwayland = {
        use_nearest_neighbor = false,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "ctrl:nocaps", -- Caps Lock acts as an extra Control
        kb_rules   = "",

        follow_mouse = 1,

        -- Hover focuses; a window sliding under a STILL pointer does not.
        --
        -- Those are two different events and mouse_refocus is the second one.
        -- With it at Hyprland's default of true, "a different window is now
        -- under the cursor" counts as a focus change even though the pointer
        -- never moved -- which is precisely what a three-finger swipe does, and
        -- the camera rule below reacts to that focus by scrolling the tape
        -- again, putting yet another window under the cursor.
        --
        -- be716f5's measurement of that loop: one swipe produced three focus
        -- changes 6 to 12 ms apart, below one frame on a 60 Hz panel, so it is
        -- invisible rather than jittery. Its control was follow_mouse = 0,
        -- where the same gestures gave 25 focus events with a MINIMUM gap of
        -- 640 ms. This is the narrower half of that control: it removes the
        -- stationary case and keeps hover-focus, which follow_mouse above still
        -- governs.
        --
        -- Measured, because an earlier note here claimed the opposite: this DOES
        -- take effect on `hyprctl reload` -- eval it to true, reload, and it
        -- comes back false. The claim that it did not came from using
        -- follow_mouse and touchpad.natural_scroll as controls, and both of
        -- those carry a config value EQUAL to their default, so "applied" and
        -- "not applied" read identically. Pick a control whose config value
        -- differs from the default, or the reading says nothing.
        mouse_refocus = false,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
-- Session menu: lock, suspend, log out, restart, shut down. This used to end the
-- session outright on a single keypress -- SUPER+M sits one key from SUPER+N and
-- there was nothing between the typo and every unsaved buffer. The menu opens on
-- Lock, and the three destructive entries need a second press to commit.
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("qs ipc call session toggle"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
-- Fullscreen, and maximize on the shifted key. Two binds because they are two
-- different things: "fullscreen" hands the window the whole output and tells the
-- client it is fullscreen, "maximized" only grows it to fill the tiling area, so
-- the gaps, the bar and any layer surface stay where they are. The
-- suppress-maximize-events rule further down does not get in the way of either
-- -- it drops maximize requests coming *from* applications, not the dispatcher.
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + tab", hl.dsp.exec_cmd(switchWindow))
-- SUPER+D and SUPER+R both open the launcher. R is the old rofi binding kept for
-- muscle memory; drop it if you never reach for it.
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
-- Audio output/input picker. The network panel opens from its bar pill instead;
-- this one has no bar entry yet, so it needs a key.
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("qs ipc call audio toggle"))
-- Theme switcher overlay. SHIFT because plain SUPER+T is togglesplit above.
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("qs ipc call theme toggle"))
-- Wallpaper picker overlay.
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("qs ipc call wallpaper toggle"))
-- Clipboard history. SHIFT because plain SUPER+V is the float toggle above, and
-- SUPER+SHIFT+V is what the cliphist docs use anyway.
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("qs ipc call clipboard toggle"))
-- The browser picker, with no link to open -- pick a browser and a profile and
-- it starts empty. This is the one thing SUPER+D cannot do: the launcher offers
-- "Google Chrome", because a chrome profile is not a desktop entry and nothing
-- in the desktop database knows the three of them exist.
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("qs ipc call browser toggle"))
-- Tiled layout picker for the focused workspace. It applies the choice with
-- `hyprctl eval` and writes it to workspace-layouts.lua, which is required back
-- in above -- so the choice survives a reload and a login. SHIFT+space rather
-- than a letter: every mnemonic one (L, T, S) is already
-- focus/move/togglesplit/special.
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.exec_cmd("qs ipc call layout toggle"))

-- The function row, for a keyboard with none of the XF86 media keys -- which is
-- most desktop keyboards, including this one. The layout is a ThinkPad's, key
-- for key: mute, volume, mic mute, brightness. That is a row a lot of hands
-- already know, and it needs none of the mnemonic letters, which ran out years
-- ago.
--
-- These duplicate the XF86 binds further down rather than replacing them: both
-- exist because either keyboard may be the one plugged in.
--
-- Volume goes straight to wpctl, while brightness goes through the shell. Not
-- an inconsistency: the OSD watches PipeWire directly, so it shows itself
-- whoever changed the volume, and wpctl needs nothing running. DDC has no such
-- channel -- BrightnessService is the only thing that can reach an external
-- monitor, and the only thing that knows what the level now is.
hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
-- -l 1 caps the raise at 100%: without it wpctl will happily amplify past unity
-- and distort, which is a strange thing for a volume key to do.
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { repeating = true })
hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind(mainMod .. " + F4", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
-- `repeating` so holding one sweeps: the service coalesces the writes.
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("qs ipc call brightness down"), { repeating = true })
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd("qs ipc call brightness up"),   { repeating = true })
-- F7 carries the row past where a ThinkPad stops: displays are the same kind of
-- thing as the six above it. The settings panel (monitor layout, and the shell
-- settings the compositor knows nothing about) is the only panel here with
-- neither a keybind nor a bar pill, so `qs ipc call settings toggle` was the
-- entire way in.
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("qs ipc call settings toggle"))

-- Jump to whatever window is asking for attention, else back to the one you came
-- from. This is Hyprland's focusurgentorlast, rebuilt: the Lua dispatcher table
-- has no urgent variant (hl.dsp exposes focus/window/workspace/group and nothing
-- else), but hl.get_urgent_window and hl.get_last_window are both there, so the
-- pieces just need assembling. focus{window=} switches workspace on its own when
-- the target lives elsewhere, which is the entire point of the bind.
--
-- Mostly a fallback since misc.focus_on_activate went on above: apps that request
-- activation properly now raise themselves when you click a notification action.
-- The ones that only set the urgent hint -- XWayland clients going through
-- _NET_ACTIVE_WINDOW, or apps that fire the action and then do nothing -- still
-- leave you with a blinking workspace pill and no way to get there.
local function focusUrgentOrLast()
    local target = hl.get_urgent_window() or hl.get_last_window()
    if target then hl.dispatch(hl.dsp.focus({ window = target })) end
end

hl.bind(mainMod .. " + U", focusUrgentOrLast)

-- Every layout message below is rejected outright by the algorithms that do not
-- implement it -- "Unknown dwindle layoutmsg: cyclenext", "no such layoutmsg for
-- scrolling" -- so anything layout-specific has to ask the workspace what it is
-- running first. hl.get_active_workspace().tiled_layout is that answer; the four
-- values it can take are the four algorithms compiled into Hyprland.

-- SUPER+T restructures the tiling under the active window, in whichever sense
-- its layout has one. This was `layout("togglesplit")` flat, which only dwindle
-- accepts -- on the other three it errored on every press:
--
--     layout     togglesplit   orientationnext   consume_or_expel
--     dwindle    ok            error             error
--     master     error         ok                error
--     monocle    error         error             error
--     scrolling  error         error             ok
--
-- Monocle has no entry because it has nothing to restructure: one window fills
-- the workspace and the rest are behind it. The key is a no-op there, which is
-- the honest result and quieter than an error in the log.
--
-- (Moved out of the app binds up top so it sits with the rest of the
-- layout-aware code. It lives on T rather than J because J is focus-down.)
local restructure = {
    dwindle   = "togglesplit",
    master    = "orientationnext",
    -- Folds the window into the neighbouring column, or gives it its own if it
    -- is already alone. Warns "no adjacent column" on the last column of the
    -- tape, where there is nothing to fold into -- use SUPER+O to expel there.
    scrolling = "consume_or_expel next",
}

hl.bind(mainMod .. " + T", function()
    local ws = hl.get_active_workspace()
    if not ws then return end

    local msg = restructure[ws.tiled_layout]
    if msg then hl.dispatch(hl.dsp.layout(msg)) end
end)

-- Cycle the window stack. Directional focus is useless on a monocle workspace
-- (every window occupies the same box), so these are how you move through it.
--
-- No single dispatcher cycles on every layout, and the generic candidates fail
-- *silently* -- they return "ok" and do nothing -- so this needs a branch:
--
--     layout     cycle_next()   cycle_next{tiled=true}   layout("cycle*")
--     dwindle    works          works                    error: Unknown
--     master     works          works                    works both ways
--     monocle    no-op          forward only             works both ways
--     scrolling  --             --                       error: no such layoutmsg
--
-- cycle_next has no reverse in any spelling. prev / previous / reverse / last /
-- backwards as table keys are all accepted and silently ignored, and every
-- positional form -- cycle_next("prev"), cycle_next({"prev","tiled"}) -- is a
-- no-op. Only the layout messages walk backwards.
local function cycleStack(dir)
    return function()
        local ws = hl.get_active_workspace()
        if not ws then return end

        -- Scrolling has no cycle message, but focus l/r walks the columns and
        -- wraps at both ends of the tape (scrolling:wrap_focus, on by default),
        -- which is the same thing and a real inverse -- no walk-forward needed.
        if ws.tiled_layout == "scrolling" then
            hl.dispatch(hl.dsp.layout(dir == "prev" and "focus l" or "focus r"))
            return
        end

        -- Master and monocle both take cyclenext/cycleprev. Preferred over the
        -- generic dispatcher for master too: it is one dispatch each way rather
        -- than the n-1 the reverse below costs.
        if ws.tiled_layout == "monocle" or ws.tiled_layout == "master" then
            hl.dispatch(hl.dsp.layout(dir == "prev" and "cycleprev" or "cyclenext"))
            return
        end

        local step = hl.dsp.window.cycle_next({ tiled = true })
        if dir ~= "prev" then
            hl.dispatch(step)
            return
        end

        -- That leaves dwindle, which has no reverse, so walk the ring forward until we land
        -- one short of where we started. Driving that with the same dispatcher
        -- makes it an exact inverse by construction, with no assumption about the
        -- order Hyprland cycles in. It runs inside a single callback, so no
        -- intermediate focus is ever composited.
        local tiled = 0
        for _, w in ipairs(ws:get_windows()) do
            if not w.floating then tiled = tiled + 1 end
        end
        for _ = 2, tiled do hl.dispatch(step) end
    end
end

hl.bind(mainMod .. " + bracketright", cycleStack("next"))
hl.bind(mainMod .. " + bracketleft",  cycleStack("prev"))

-- Column controls for the scrolling layout. The tape is wider than the monitor
-- by design, so it needs keys the other three layouts have no use for: move the
-- viewport along it, move a column within it, and set how wide a column is.
--
-- Gated on the layout rather than bound flat. Every message here is rejected by
-- dwindle/master/monocle, and a flat bind would mean four keys that log an error
-- on every press outside a scrolling workspace.
local function scrollingMsg(msg)
    return function()
        local ws = hl.get_active_workspace()
        if not ws or ws.tiled_layout ~= "scrolling" then return end
        hl.dispatch(hl.dsp.layout(msg))
    end
end

-- Three fingers step the tape one column; four switch workspaces.
--
-- Declared HERE rather than beside the other input settings, because the action
-- is scrollingMsg and Lua needs it to exist first. That is also why the block
-- reads oddly far from hl.device: it follows the helper, not the topic.
--
-- `left` and `right` rather than one `horizontal`. Measured: the two cannot
-- coexist -- registering `left` while a `horizontal` is present is refused with
-- "Previous HORIZONTAL shadows new LEFT" -- so this replaces the old
-- `action = "scroll_move"` rather than sitting beside it.
--
-- What that trades away. scroll_move moved the tape 1:1 against the viewport
-- while the fingers were down and snapped to a column on release
-- (ScrollMoveGesture.cpp), so one long swipe could travel several columns and
-- the tape tracked your fingers the whole way. These step exactly one column
-- per swipe and the tape jumps. That is the behaviour that was asked for, and
-- the continuous version is one `direction = "horizontal", action =
-- "scroll_move"` away if it is ever missed.
--
-- A function action receives NO arguments -- measured, `args=0` across six
-- swipes -- which is why the direction has to come from two registrations
-- rather than from a parameter. scrollingMsg already returns a zero-argument
-- function, so it is the right shape as well as the right gate: off a
-- scrolling workspace a layout message is an error per swipe.
--
-- The left/right mapping matches how scroll_move behaved: fingers left, tape
-- left, columns from the right come into view. It could not be tested before
-- landing, because `left` is refused while `horizontal` is registered and a
-- gesture change does not survive `hyprctl reload` -- it needs a fresh login.
-- If it feels inverted, swap the two message strings.
hl.gesture({ fingers = 3, direction = "left",  action = scrollingMsg("move +col") })
hl.gesture({ fingers = 3, direction = "right", action = scrollingMsg("move -col") })

hl.gesture({
    fingers = 4,
    direction = "horizontal",
    action = "workspace",
})

-- Move focus one column each way, carrying the camera with it.
--
-- This comment used to say the two keys scrolled the viewport and left focus
-- where it was. They do not: `move -col` focuses the previous column and warps
-- the cursor into it (ScrollingAlgorithm.cpp:1414-1439), and a measurement
-- shows the focused window's address changing on every press. They differ from
-- SUPER+H/L only in being column-wise rather than spatial, and in the warp.
hl.bind(mainMod .. " + comma",  scrollingMsg("move -col"))
hl.bind(mainMod .. " + period", scrollingMsg("move +col"))

-- Move the focused column along the tape. Wraps at both ends by default
-- (scrolling:wrap_swapcol), so a column can be sent from one end to the other.
hl.bind(mainMod .. " + SHIFT + comma",  scrollingMsg("swapcol l"))
hl.bind(mainMod .. " + SHIFT + period", scrollingMsg("swapcol r"))


-- Column width. The steps are fractions of the monitor, matching
-- scrolling:column_width; +conf cycles the preset widths in
-- scrolling:explicit_column_widths, which is usually the one you want. That
-- list is set above and is NOT the stock one: every preset there is chosen so
-- that a set of columns which fits stays strictly under the monitor width,
-- which is what makes focus_fit_method = 0 center on overflow only. Read the
-- comment beside column_width before changing a number here.
hl.bind(mainMod .. " + minus",         scrollingMsg("colresize -0.1"))
hl.bind(mainMod .. " + equal",         scrollingMsg("colresize +0.1"))
hl.bind(mainMod .. " + SHIFT + equal", scrollingMsg("colresize +conf"))

-- Grow the focused column into whatever space is left on the monitor, and pull
-- a column that has scrolled half off back into view.
hl.bind(mainMod .. " + G",         scrollingMsg("fit expand"))
hl.bind(mainMod .. " + SHIFT + G", scrollingMsg("fit_into_view"))

-- Stack windows into one column and pull them back out again. SUPER+T does both
-- in one key (see restructure above); these are the explicit halves, and the
-- only way out of the last column on the tape, where SUPER+T has no neighbour
-- to fold into.
--
-- There is also a `promote` message, left unbound: it does exactly what expel
-- does -- new column immediately right of the one the window left, rest of the
-- stack closing up -- in every position tried, top, middle and bottom of a
-- stack, first and last column. The only difference is on a window that is
-- already alone in its column, where expel warns "column has only one window"
-- and promote returns ok. Both no-op.
hl.bind(mainMod .. " + I", scrollingMsg("consume"))
hl.bind(mainMod .. " + O", scrollingMsg("expel"))

-- Move focus with mainMod + arrow keys. Plain dispatchers: the camera rule
-- rides on window.active, so every one of these gets it without asking.
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Same thing, vim-style. Note these do nothing on the monocle workspace, where
-- every window occupies the same box -- use the bracket binds above there.
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))

-- Move the active window in a direction. Same monocle caveat as above: with
-- every window in the same box there is nowhere to move it to.
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))

-- Cross monitors explicitly. The plain directional binds above already fall off
-- the edge onto the next monitor -- that is binds:window_direction_monitor_fallback,
-- on by default -- but only when there is no window that way on the current one.
-- On the scrolling layout the tape extends past both screen edges, so there is
-- almost always another column to move to first and the fallback never fires.
-- These do not care what is on screen.
hl.bind(mainMod .. " + CTRL + H", hl.dsp.focus({ monitor = "l" }))
hl.bind(mainMod .. " + CTRL + L", hl.dsp.focus({ monitor = "r" }))

-- Throw the active window at the other monitor. Focus follows it.
hl.bind(mainMod .. " + CTRL + SHIFT + H", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mainMod .. " + CTRL + SHIFT + L", hl.dsp.window.move({ monitor = "r" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
-- SUPER+wheel steps the tape, the mouse counterpart of the three-finger swipe.
-- It used to change workspace; that lives on SUPER+<number> and the four-finger
-- gesture, and a mouse had no way to walk the columns at all.
hl.bind(mainMod .. " + mouse_down", scrollingMsg("move +col"))
hl.bind(mainMod .. " + mouse_up",   scrollingMsg("move -col"))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
-- Brightness through the shell rather than straight to brightnessctl. Two
-- reasons. It is the only way to reach an external monitor at all -- those have
-- no kernel backlight device, so their brightness lives in the monitor firmware
-- and is written over DDC/CI, which BrightnessService does. And bare
-- `brightnessctl set` is actively wrong on a machine with no backlight class:
-- it falls through to the first device of any class it finds, which here is
-- `input1::numlock`, so these two binds used to toggle the numlock LED.
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("qs ipc call brightness up"),                       { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("qs ipc call brightness down"),                     { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


---------------------
---- SCREENSHOTS ----
---------------------

-- grim captures, slurp picks the region, wl-copy puts it on the clipboard.
-- `tee` also drops a timestamped copy in ~/Pictures/Screenshots, so a shot is
-- not lost the moment something else overwrites the clipboard.
--
-- The region bind guards on slurp's exit status: pressing Escape to cancel makes
-- slurp exit non-zero, and without the guard grim would be handed an empty
-- geometry and tee would leave a 0-byte file behind.
local shotDir  = [["$HOME/Pictures/Screenshots"]]
local shotFile = [["$HOME/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png"]]

local function shot(grimArgs, guard)
    return hl.dsp.exec_cmd(
        "mkdir -p " .. shotDir .. "; " .. (guard or "") ..
        "grim " .. grimArgs .. " - | tee " .. shotFile .. " | wl-copy"
    )
end

-- Print               -> drag out a region
-- SHIFT + Print       -> the whole monitor you are currently on
-- SUPER + Print       -> just the focused window
hl.bind("Print",                  shot([[-g "$g"]], [[g=$(slurp) || exit 0; ]]))
hl.bind("SHIFT + Print",          shot([[-o "$(hyprctl -j activeworkspace | jq -r .monitor)"]]))
hl.bind(mainMod .. " + Print",    shot([[-g "$(hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')"]]))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- The bar draws its background, and optionally its pills, at less than full
-- alpha so the wallpaper reads through. Layer surfaces are not blurred by
-- default -- only windows are -- so without this the bar is a clear window onto
-- whatever is behind it, and the text sitting on it is only as readable as the
-- wallpaper allows. Everything quickshell puts on screen shares the one
-- namespace, so this covers the panels and popups too; they are opaque, so for
-- them it is a no-op.
--
-- ignore_alpha leaves fully transparent pixels alone, which is what makes a 0%
-- strip with translucent pills blur behind the pills only, rather than frosting
-- a band across the top of the screen.
--
-- On/off is the settings panel's, in quickshell/bar.conf beside the two alphas
-- it belongs with. The panel applies it live with `hyprctl eval`; reading it
-- back here is what survives a reload, exactly like theme-borders.conf above.
local function barBlur()
    -- quickshell's state, moved there by spec 2. This read still pointed at the
    -- old ~/.config path, which spec 2 emptied.
    local f = io.open("@quickshellState@/bar.conf", "r")
    if not f then return true end

    local blur = true
    for line in f:lines() do
        local v = line:match("^blur%s*=%s*(%d+)")
        if v then blur = tonumber(v) ~= 0 end
    end
    f:close()

    return blur
end

hl.layer_rule({
    name         = "blur-quickshell",
    match        = { namespace = "^quickshell$" },
    blur         = barBlur(),
    ignore_alpha = 0.05,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
